# Generated by Django 2.0.2 on 2018-05-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='context',
        ),
    ]
