# Generated by Django 2.0.2 on 2018-06-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180604_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='userId',
            new_name='user',
        ),
    ]
