# Generated by Django 2.0.2 on 2018-06-06 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20180605_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count_of_voters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
