# Generated by Django 2.0.2 on 2018-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_votedusersonpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='shop/uploads/'),
        ),
    ]
